theme: jekyll-theme-minimal

title: DERBI

description: 
DERBI is a secure protocol that enables interoperability for both public and private blockchains in a decentralised way, having public escrow parties (PEWPs) as cross-blockchain distributors. 

avatar: "logo.png"
